[project]
name = "ai-study-group"
version = "0.1.0"
description = "AI Study Group project with embedding similarity"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.0",
    "openai>=1.0.0",
]

